# Generated by Django 3.2.18 on 2023-03-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('job_count', models.PositiveIntegerField(default=0)),
                ('resume_count', models.PositiveIntegerField(default=0)),
                ('web_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
