# Generated by Django 3.2.18 on 2023-03-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20230318_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_employees_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_employees_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
