# Generated by Django 3.2.18 on 2023-03-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20230320_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=255)),
                ('matched_job_count', models.IntegerField(blank=True, null=True)),
                ('matched_company_count', models.IntegerField(blank=True, null=True)),
                ('matched_skill_count', models.IntegerField(blank=True, null=True)),
                ('matched_role_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
