# Generated by Django 3.2.18 on 2023-03-21 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20230321_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='company',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.email'),
        ),
    ]
