# Generated by Django 3.2.18 on 2023-03-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20230324_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email_from',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='email_from',
            new_name='from_email',
        ),
    ]
