# Generated by Django 3.2.18 on 2023-03-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20230324_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
