# Generated by Django 3.2.18 on 2023-03-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_email_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='focus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='job_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='url_structure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
