# Generated by Django 3.2.18 on 2023-03-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20230328_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='reply_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='to_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
