# Generated by Django 3.2.18 on 2023-04-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20230402_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='company',
            field=models.ManyToManyField(related_name='skills', to='website.Company'),
        ),
    ]
