# Generated by Django 3.2.18 on 2023-04-04 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0021_skill_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='company',
            new_name='companies',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='created',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='modified',
        ),
        migrations.AddField(
            model_name='skill',
            name='users',
            field=models.ManyToManyField(related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
