# Generated by Django 3.2.18 on 2023-06-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20230404_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link_status_code',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
    ]
