# Generated by Django 4.2.2 on 2023-06-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0025_company_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="company_screenshots"
            ),
        ),
    ]
