# Generated by Django 4.2.2 on 2023-07-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0026_company_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
