# Generated by Django 4.2.2 on 2023-07-04 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0027_job_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
