# Generated by Django 4.2.2 on 2023-07-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0031_job_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="remote",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
