# Generated by Django 4.2.2 on 2023-07-15 22:27

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0033_job_search_vector_job_website_job_search__0dd667_gin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
