# Generated by Django 4.2.7 on 2023-11-09 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0037_bouncedemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes"),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures"
                    ),
                ),
                ("resume_views", models.PositiveIntegerField(default=0)),
                ("web_views", models.PositiveIntegerField(default=0)),
                ("resume_download_count", models.PositiveIntegerField(default=0)),
                ("resume_download_limit", models.PositiveIntegerField(default=0)),
                (
                    "links",
                    models.ManyToManyField(related_name="profiles", to="website.link"),
                ),
                (
                    "roles",
                    models.ManyToManyField(related_name="profiles", to="website.role"),
                ),
                (
                    "skills",
                    models.ManyToManyField(related_name="profiles", to="website.skill"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
