# Generated by Django 4.2.7 on 2023-11-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0038_link_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
