# Generated by Django 4.2.7 on 2023-11-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0041_link_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="links",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="profiles", to="website.link"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="roles",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="profiles", to="website.role"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="profiles", to="website.skill"
            ),
        ),
    ]
