# Generated by Django 4.2.7 on 2024-07-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0042_alter_profile_links_alter_profile_roles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="reply_to",
        ),
        migrations.RemoveField(
            model_name="email",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="email",
            name="to_email",
        ),
        migrations.AlterField(
            model_name="profile",
            name="links",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="website.link"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="website.role"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="website.skill"
            ),
        ),
    ]
