# Generated by Django 4.2.7 on 2024-07-16 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0043_remove_email_reply_to_remove_email_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="from_email",
        ),
    ]
