# Generated by Django 4.2.7 on 2024-08-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0048_alter_requestlog_referer"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="link_status_code_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
