# Generated by Django 4.2.7 on 2024-08-15 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0049_job_link_status_code_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
