# Generated by Codex for profile-scoped OpenAI key storage.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0052_job_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="openai_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
