# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0053_profile_openai_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cover_letter_prompt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_letter_profiles",
                to="website.prompt",
            ),
        ),
    ]
